#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

foamCleanTutorials
runApplication blockMesh
runApplication setFields
#runApplication kfvsFoam
runApplication densityFoam
#runApplication rhoCentralFoam  //pimple
runApplication -s sample  postProcess -func sample -latestTime
./createGraphs

#------------------------------------------------------------------------------
