#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------


foamCleanTutorials
runApplication blockMesh
runApplication setFields
touch case.foam
runApplication barotropicFoam


#------------------------------------------------------------------------------
