IOdictionary physicalProperties
(
    IOobject 
    (
        "physicalProperties",
        runTime.constant(),
        mesh,
        IOobject::MUST_READ_IF_MODIFIED,
        IOobject::NO_WRITE
    )
);
volScalarField T
(
    IOobject
    (
        "T",
        runTime.timeName(),
        mesh,
        IOobject::MUST_READ,
        IOobject::AUTO_WRITE
    ),
    mesh
);
volVectorField U
(
    IOobject
    (
        "U",
        runTime.timeName(),
        mesh,
        IOobject::MUST_READ,
        IOobject::AUTO_WRITE
    ),
    mesh
);
dimensionedScalar deltaN("deltaN", inv(dimLength), 1e-8);
dimensionedScalar gamma(physicalProperties.lookup("gamma"));
dimensionedScalar DT(physicalProperties.lookup("DT"));
