#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

. $WM_PROJECT_DIR/bin/tools/RunFunctions

foamCleanTutorials
runApplication blockMesh
runApplication setFields
touch case.foam
runApplication phaseFieldFoam


#------------------------------------------------------------------------------
